title: "My Astrological Journey"
description: "Exploring the cosmos"
url: "https://parishodana.xyz" # Replace with your actual GitHub URL
baseurl: "/blog" 

markdown: kramdown
permalink: /:year/:month/:day/:title/

# This tells Jekyll to use your custom html layouts, not a pre-made theme
theme: null 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
include: [_posts, blog] # This ensures it looks for posts


